calendar
monyatto/ruby-practices pull request #1
Opened 2021-09-01 23:24 UTC by monyatto

カレンダープログラムを追加しました。

2021-09-07 07:50 UTC, u1tnk requested changes
コメントしました！

2021-09-07 07:50 UTC, u1tnk commented on 01.fizzbuzz/fizzbuzz.rb
> +(1..20).each do |num|
FizzBuzz課題が残っちゃってますね。
mainブランチにマージ済みならここに差分としては出ないので、mainブランチにコミットをpushしてしまいましょう。
と、確認したらFizzBuzzとCalendarが一つのコミットになっちゃってますね。
分ける事は可能ですが大変なので、今回は良いですが、次回の課題から気をつけてくださいね。

2021-09-07 07:50 UTC, u1tnk commented on 02.calendar/calendar.rb
> +if  ARGV[0] == "-y"
OptionParser使っていれば ARGV配列を使うことは無いはずですので、使い方をもう一度確認してみてください。

https://docs.ruby-lang.org/ja/latest/class/OptionParser.html

2021-09-07 07:50 UTC, u1tnk commented on 02.calendar/calendar.rb
> +  if firstday_switch == true && day_of_week != 7
これは最初だけ特別にする分けですよね？
フラグをたくさん作ると分かりづらくなるので、既存の情報を使うようにしてみましょう。

2021-09-07 07:50 UTC, u1tnk commented on 02.calendar/calendar.rb
> +  days_number += 1
ループごとに1足していると思うのですが、 `10.times { |i|  p i} `というようにブロック引数を定義すれば0から増えていくのでそちらを使えると重いますよ。

2021-09-07 07:50 UTC, u1tnk commented on 02.calendar/calendar.rb
> +    if Date.today.day == Date.new(year, month, days_number).day
ここはインデントがおかしいと思います。
また、 ifとendの間に空行を入れると見やすくなりますよ。

2021-09-07 07:50 UTC, u1tnk commented on 02.calendar/calendar.rb
> +      print Paint["#{space}#{Date.new(year, month, days_number).day}", :inverse]
日付反転できてますね 👍

2021-09-07 07:50 UTC, u1tnk commented on 02.calendar/calendar.rb
> +    if Date.today.day == Date.new(year, month, days_number).day
`Date.new(year, month, days_number)` が何回も出てくるのでブロックの先頭にでも変数化した方が良いですね。
一般に3回以上繰り返すコードは短くてもまとめると良いと言われます。

2021-09-07 07:50 UTC, u1tnk commented on 02.calendar/calendar.rb
> +  if Date.new(year, month, days_number).cwday == 6
こういう処理内容が一行のものは
```
print "\n" if  Date.new(year, month, days_number).cwday == 6
```

と一行で書けますよ。

2021-09-09 00:29 UTC, monyatto commented
ご指摘いただいた点、修正いたしました！mm

2021-09-09 02:10 UTC, u1tnk approved these changes
コメントはしましたが、問題無いですね 🙆‍♀️

2021-09-09 02:10 UTC, u1tnk commented on 02.calendar/calendar.rb
> +opt.on('-y [year]', Integer) { |val| year = val if val != nil }
改善しましたね 👍  
オプションがあるときだけ呼ばれるはずなので、 `if val ...`のところはいらないと思いますので確認してみてください。

2021-09-09 22:12 UTC, merged